liste_deroulante_map = list(`[HH030] Number of rooms available to the household` = "HH030_moy",
                            `[RB031] Year of immigration` = "RB031_moy",
                            `[PL200] Number of years spent in paid work` = "PL200_moy",
                            `[HH060] Current rent related to occupied dwelling` = "HH060_moy",
                            `[HH061] Subjective rent` = "HH061_moy",
                            `[HH070] Total housing cost` = "HH070_moy",
                            `[HY010] Total household gross income` = "HY010_moy",
                            `[HY020] Total disposable household income` = "HY020_moy",
                            `[PB140] Year of birth` = "PB140_moy",
                            `[PL060] Number of hours usually worked per week in min job` = "PL060_moy",
                            `[PL100] Total number of hours usually worked in second, third, … jobs` = "PL100_moy",
                            `[HS180] Pollution, grime or other environment problems` = "HS180_moy",
                            `[HS190] Crime, violence or vandalism in the area` = "HS190_moy",
                            `[HH040] Leaking roof, damp walls/floors/foundation, or rot in window frames or floor` = "HH040_moy",
                            `[HH050] Ability to keep home adequately warm` = "HH050_moy",
                            `[HS160] Problems with the dwelling: too dark, not enough light` = "HS160_moy",
                            `[PL015] Whether person has ever worked` = "PL015_moy",
                            `[PL160] Change of job since last year` = "PL160_moy",
                            `[HH040] Leaking roof, damp walls/floors/foundation, or rot in window frames or floor` = "HH040_moy",
                            `[PL140] Type of contract` = c(`Permanent job/work contract of unlimited duration`="PL140.1_moy",
                                                           `Temporary job/work contract of limited duration`="PL140.2_moy"),
                            `[PE010] Current education activity` = c(`In education`="PE010.1_moy",
                                                                     `Not in education`="PE010.2_moy"),
                            `[PB150] Sex` = c(`Male`="PB150.1_moy",
                                              `Female` = "PB150.2_moy"),
                            `[RB200] Residential status` = c(`Currently living in the household`="RB200.1_moy",
                                                     `Temporarily absent`="RB200.2_moy"),
                            `[HH010] Dwelling type` = c(`Detached house` = "HH010.1_moy",
                                                        `Semi-detached or terraced house` = "HH010.2_moy",
                                                        `Apartment or flat in a building with less than 10 dwellings` = "HH010.3_moy",
                                                        `Apartment or flat in a building with 10 or more dwellings` = "HH010.4_moy",
                                                        `Some other kind of accomodation` = "HH010.5_moy"),
                            `[HS021] Arrears on utility bills` = c(`Yes, once` = "HS021.1_moy",
                                                                   `Yes, twice or more` = "HS021.2_moy",
                                                                   `No` = "HS021.3_moy"),
                            `[HH021] Tenure status` = c(`Outright owner` = "HH021.1_moy",
                                                        `Owner paying mortgage` = "HH021.2_moy",
                                                        `Tenant or subtenant paying rent at prevailing or market rate` = "HH021.3_moy",
                                                        `Accommodation is rented at a reduced rate (lower price than the market price)` = "HH021.4_moy",
                                                        `Accomodation is provided free` = "HH021.5_moy"),
                            `[RB210] Basic activities status` = c(`At work` = "RB210.1_moy",
                                                                  `Unemployed` = "RB210.2_moy",
                                                                  `In retirement or early retirement or has given up business` = "RB210.3_moy",
                                                                  `Other inactive person` = "RB210.4_moy"),
                            `[PE020] ISCED level currently attended` = c(`Primary education` = "PE020.1_moy",
                                                                         `Lower secondary education` = "PE020.2_moy",
                                                                         `Upper secondary education` = "PE020.3_moy",
                                                                         `Post-secondary non tertiary education` = "PE020.4_moy",
                                                                         `First stage of tertiary education (not leading directly to an advanced research qualification` = "PE020.5_moy",
                                                                         `Second stage of tertiary education (leaving to an advanced research qualification` = "PE020.6_moy"),
                            `[PE040] Highest ISCED level attended` = c(`Pre-primary education` = "PE040.0_moy",
                                                                       `Primary education` = "PE040.1_moy",
                                                                       `Lower secondary education` = "PE040.2_moy",
                                                                       `Upper secondary education` = "PE040.3_moy",
                                                                       `Post-secondary non tertiary education` = "PE040.4_moy",
                                                                       `First stage of tertiary education (not leading directly to an advanced research qualification` = "PE040.5_moy",
                                                                       `Second stage of tertiary education (leaving to an advanced research qualification` = "PE040.6_moy"),
                            `[PL031] Self-defined current economic status` = c(`Employee working full-time` = "PL031.1_moy",
                                                                               `Employee working part-time` = "PL031.2_moy",
                                                                               `Self-employed working full-time (including family worker)` = "PL031.3_moy",
                                                                               `Self-employed working part-time (including family worker)` = "PL031.4_moy",
                                                                               `Unemployed` = "PL031.5_moy",
                                                                               `Pupil, student, further training unpaid work experience` = "PL031.6_moy",
                                                                               `In retirement or in early retirement or has given up business` = "PL031.7_moy",
                                                                               `Permanently disabled or/and unfit to work` = "PL031.8_moy",
                                                                               `In compulsory military or community service` = "PL031.9_moy",
                                                                               `Fulfilling domestic tasks and care responsibilities` = "PL031.10_moy",
                                                                               `Other inactive person` = "PL031.11_moy"),
                            `[HH081] Bath or shower in dwelling` = c(`Yes, for sole use of the household` = "HH081.1_moy",
                                                                     `Yes, shared` = "HH081.2_moy",
                                                                     `No` = "HH081.3_moy"),
                            `[PL051] Occupation (ISCO-08 (COM))` = c(`Managers` = "PL051.1_moy",
                                                                     `Chief Executives, Senior Officials and Legislators` = "PL051.11_moy",
                                                                     `Administrative and Commercial Managers` = "PL051.12_moy",
                                                                     `Production and Specialized Services Managers` = "PL051.13_moy",
                                                                     `Hospitality, Retail and Other Services Managers` = "PL051.14_moy",
                                                                     `Professionals` = "PL051.2_moy",
                                                                     `Science and Engineering Professionals` = "PL051.21_moy",
                                                                     `Health Professionals` = "PL051.22_moy",
                                                                     `Teaching Professionals` = "PL051.23_moy",
                                                                     `Business and Administration Professionals` = "PL051.24_moy",
                                                                     `Information and Communications Technology Professionals` = "PL051.25_moy",
                                                                     `Legal, Social and Cultural Professionals` = "PL051.26_moy",
                                                                     `Technicians and Associate Professionals` = "PL051.3_moy",
                                                                     `Science and Engineering Associate Professionals` = "PL051.31_moy",
                                                                     `Health Associate Professionals` = "PL051.32_moy",
                                                                     `Business and Administration Associate Professionals` = "PL051.33_moy",
                                                                     `Legal, Social, Cultural and Related Associate Professionals` = "PL051.34_moy",
                                                                     `Information and Communications Technicians` = "PL051.35_moy",
                                                                     `Clerical Support Workers` = "PL051.4_moy",
                                                                     `General and Keyboard Clerks` = "PL051.41_moy",
                                                                     `Customer Services Clerks` = "PL051.42_moy",
                                                                     `Numerical and Material Recording Clerks` = "PL051.43_moy",
                                                                     `Other Clerical Support Workers` = "PL051.44_moy",
                                                                     `Services and Sales Workers` = "PL051.5_moy",
                                                                     `Personal Services Workers` = "PL051.51_moy",
                                                                     `Sales Workers` = "PL051.52_moy",
                                                                     `Personal Care Workers` = "PL051.53_moy",
                                                                     `Protective Services Workers` = "PL051.54_moy",
                                                                     `Skilled Agricultural, Forestry and Fishery Workers` = "PL051.6_moy",
                                                                     `Market-oriented Skilled Agricultural Workers` = "PL051.61_moy",
                                                                     `Market-oriented Skilled Forestry, Fishery and Hunting Workers` = "PL051.62_moy",
                                                                     `Craft and Related Trades Workers` = "PL051.7_moy",
                                                                     `Building and Related Trades Workers (excluding Electricians)` = "PL051.71_moy",
                                                                     `Metal, Machinery and Related Trades Workers` = "PL051.72_moy",
                                                                     `Handicraft and Printing Workers` = "PL051.73_moy",
                                                                     `Electrical and Electronics Trades Workers` = "PL051.74_moy",
                                                                     `Food Processing, Woodworking, Garment and Other Craft and Related Trades Workers` = "PL051.75_moy",
                                                                     `Plant and Machine Operators and Assemblers` = "PL051.8_moy",
                                                                     `Stationary Plant and Machine Operators` = "PL051.81_moy",
                                                                     `Assemblers` = "PL051.82_moy",
                                                                     `Drivers and Mobile Plant Operators` = "PL051.83_moy",
                                                                     `Elementary Occupations` = "PL051.9_moy",
                                                                     `Cleaners and Helpers` = "PL051.91_moy",
                                                                     `Agricultural, Forestry and Fishery Labourers` = "PL051.92_moy",
                                                                     `Labourers in Mining, Construction, Manufacturing and Transport` = "PL051.93_moy",
                                                                     `Food Preparation Assistants` = "PL051.94_moy",
                                                                     `Street and Related Sales and Services Workers` = "PL051.95_moy",
                                                                     `Refuse Workers and Other Elementary Workers` = "PL051.96_moy")
)