liste_deroulante_map = list(`[HH030] Number of rooms available to the household` = "HH030_moy",
                            `[RB031] Year of immigration` = "RB031_moy",
                            `[PL200] Number of years spent in paid work` = "PL200_moy",
                            `[HH060] Current rent related to occupied dwelling` = "HH060_moy",
                            `[HH061] Subjective rent` = "HH061_moy",
                            `[HH070] Total housing cost` = "HH070_moy",
                            `[HY010] Total household gross income` = "HY010_moy",
                            `[HY020] Total disposable household income` = "HY020_moy",
                            `[PB140] Year of birth` = "PB140_moy",
                            `[PL060] Number of hours usually worked per week in min job` = "PL060_moy",
                            `[PL100] Total number of hours usually worked in second, third, … jobs` = "PL100_moy",
                            `[HS180] Pollution, grime or other environment problems` = "HS180_moy",
                            `[HS190] Crime, violence or vandalism in the area` = "HS190_moy",
                            `[HH040] Leaking roof, damp walls/floors/foundation, or rot in window frames or floor` = "HH040_moy",
                            `[HH050] Ability to keep home adequately warm` = "HH050_moy",
                            `[HS160] Problems with the dwelling: too dark, not enough light` = "HS160_moy",
                            `[PL015] Whether person has ever worked` = "PL015_moy",
                            `[PL160] Change of job since last year` = "PL160_moy",
                            `[DB100] Degree of urbanisation` = c(`[DB100] Degree of urbanisation : Densely-populated area` = "DB100.1_moy",
                                                                 `[DB100] Degree of urbanisation : Intermediate area` = "DB100.2_moy",
                                                                 `[DB100] Degree of urbanisation : Thinly-populated area` = "DB100.3_moy"),
                            `[PL140] Type of contract` = c(`[PL140] Type of contract : Permanent job/work contract of unlimited duration`="PL140.1_moy",
                                                           `[PL140] Type of contract : Temporary job/work contract of limited duration`="PL140.2_moy"),
                            `[PE010] Current education activity` = c(`[PE010] Current education activity : In education`="PE010.1_moy",
                                                                     `[PE010] Current education activity : Not in education`="PE010.2_moy"),
                            `[PB150] Sex` = c(`[PB150] Sex : Male`="PB150.1_moy",
                                              `[PB150] Sex : Female` = "PB150.2_moy"),
                            `[RB200] Residential status` = c(`[RB200] Residential status : Currently living in the household`="RB200.1_moy",
                                                             `[RB200] Residential status : Temporarily absent`="RB200.2_moy"),
                            `[HH010] Dwelling type` = c(`[HH010] Dwelling type : Detached house` = "HH010.1_moy",
                                                        `[HH010] Dwelling type : Semi-detached or terraced house` = "HH010.2_moy",
                                                        `[HH010] Dwelling type : Apartment or flat in a building with less than 10 dwellings` = "HH010.3_moy",
                                                        `[HH010] Dwelling type : Apartment or flat in a building with 10 or more dwellings` = "HH010.4_moy",
                                                        `[HH010] Dwelling type : Some other kind of accomodation` = "HH010.5_moy"),
                            `[HS021] Arrears on utility bills` = c(`[HS021] Arrears on utility bills : Yes, once` = "HS021.1_moy",
                                                                   `[HS021] Arrears on utility bills : Yes, twice or more` = "HS021.2_moy",
                                                                   `[HS021] Arrears on utility bills : No` = "HS021.3_moy"),
                            `[HH021] Tenure status` = c(`[HH021] Tenure status : Outright owner` = "HH021.1_moy",
                                                        `[HH021] Tenure status : Owner paying mortgage` = "HH021.2_moy",
                                                        `[HH021] Tenure status : Tenant or subtenant paying rent at prevailing or market rate` = "HH021.3_moy",
                                                        `[HH021] Tenure status : Accommodation is rented at a reduced rate (lower price than the market price)` = "HH021.4_moy",
                                                        `[HH021] Tenure status : Accomodation is provided free` = "HH021.5_moy"),
                            `[RB170] Main activity status` = c(`[RB170] Main activity status : At work` = "RB170.1_moy",
                                                                  `[RB170] Main activity status : Unemployed` = "RB170.2_moy",
                                                                  `[RB170] Main activity status : In retirement or early retirement or has given up business` = "RB170.3_moy",
                                                                  `[RB170] Main activity status : Other inactive person` = "RB170.4_moy"),
                            `[RB210] Basic activities status` = c(`[RB210] Main activity status : At work` = "RB210.1_moy",
                                                                  `[RB210] Main activity status : Unemployed` = "RB210.2_moy",
                                                                  `[RB210] Main activity status : In retirement or early retirement or has given up business` = "RB210.3_moy",
                                                                  `[RB210] Main activity status : Other inactive person` = "RB210.4_moy"),
                            `[PE020] ISCED level currently attended` = c(`[PE020] ISCED level currently attended : Primary education` = "PE020.1_moy",
                                                                         `[PE020] ISCED level currently attended : Lower secondary education` = "PE020.2_moy",
                                                                         `[PE020] ISCED level currently attended : Upper secondary education` = "PE020.3_moy",
                                                                         `[PE020] ISCED level currently attended : Post-secondary non tertiary education` = "PE020.4_moy",
                                                                         `[PE020] ISCED level currently attended : First stage of tertiary education (not leading directly to an advanced research qualification` = "PE020.5_moy",
                                                                         `[PE020] ISCED level currently attended : Second stage of tertiary education (leaving to an advanced research qualification` = "PE020.6_moy"),
                            `[PE040] Highest ISCED level attended` = c(`[PE040] Highest ISCED level attended : Pre-primary education` = "PE040.0_moy",
                                                                       `[PE040] Highest ISCED level attended : Primary education` = "PE040.1_moy",
                                                                       `[PE040] Highest ISCED level attended : Lower secondary education` = "PE040.2_moy",
                                                                       `[PE040] Highest ISCED level attended : Upper secondary education` = "PE040.3_moy",
                                                                       `[PE040] Highest ISCED level attended : Post-secondary non tertiary education` = "PE040.4_moy",
                                                                       `[PE040] Highest ISCED level attended : First stage of tertiary education (not leading directly to an advanced research qualification` = "PE040.5_moy",
                                                                       `[PE040] Highest ISCED level attended : Second stage of tertiary education (leaving to an advanced research qualification` = "PE040.6_moy"),
                            `[PL031] Self-defined current economic status` = c(`[PL031] Self-defined current economic status : Employee working full-time` = "PL031.1_moy",
                                                                               `[PL031] Self-defined current economic status : Employee working part-time` = "PL031.2_moy",
                                                                               `[PL031] Self-defined current economic status : Self-employed working full-time (including family worker)` = "PL031.3_moy",
                                                                               `[PL031] Self-defined current economic status : Self-employed working part-time (including family worker)` = "PL031.4_moy",
                                                                               `[PL031] Self-defined current economic status : Unemployed` = "PL031.5_moy",
                                                                               `[PL031] Self-defined current economic status : Pupil, student, further training unpaid work experience` = "PL031.6_moy",
                                                                               `[PL031] Self-defined current economic status : In retirement or in early retirement or has given up business` = "PL031.7_moy",
                                                                               `[PL031] Self-defined current economic status : Permanently disabled or/and unfit to work` = "PL031.8_moy",
                                                                               `[PL031] Self-defined current economic status : In compulsory military or community service` = "PL031.9_moy",
                                                                               `[PL031] Self-defined current economic status : Fulfilling domestic tasks and care responsibilities` = "PL031.10_moy",
                                                                               `[PL031] Self-defined current economic status : Other inactive person` = "PL031.11_moy"),
                            `[HH081] Bath or shower in dwelling` = c(`[HH081] Bath or shower in dwelling : Yes, for sole use of the household` = "HH081.1_moy",
                                                                     `[HH081] Bath or shower in dwelling : Yes, shared` = "HH081.2_moy",
                                                                     `[HH081] Bath or shower in dwelling : No` = "HH081.3_moy"),
                            `[PL051] Occupation (ISCO-08 (COM))` = c(`[PL051] Occupation (ISCO-08 (COM)) : Managers` = "PL051.1_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Chief Executives, Senior Officials and Legislators` = "PL051.11_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Administrative and Commercial Managers` = "PL051.12_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Production and Specialized Services Managers` = "PL051.13_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Hospitality, Retail and Other Services Managers` = "PL051.14_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Professionals` = "PL051.2_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Science and Engineering Professionals` = "PL051.21_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Health Professionals` = "PL051.22_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Teaching Professionals` = "PL051.23_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Business and Administration Professionals` = "PL051.24_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Information and Communications Technology Professionals` = "PL051.25_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Legal, Social and Cultural Professionals` = "PL051.26_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Technicians and Associate Professionals` = "PL051.3_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Science and Engineering Associate Professionals` = "PL051.31_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Health Associate Professionals` = "PL051.32_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Business and Administration Associate Professionals` = "PL051.33_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Legal, Social, Cultural and Related Associate Professionals` = "PL051.34_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Information and Communications Technicians` = "PL051.35_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Clerical Support Workers` = "PL051.4_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : General and Keyboard Clerks` = "PL051.41_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Customer Services Clerks` = "PL051.42_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Numerical and Material Recording Clerks` = "PL051.43_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Other Clerical Support Workers` = "PL051.44_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Services and Sales Workers` = "PL051.5_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Personal Services Workers` = "PL051.51_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Sales Workers` = "PL051.52_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Personal Care Workers` = "PL051.53_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Protective Services Workers` = "PL051.54_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Skilled Agricultural, Forestry and Fishery Workers` = "PL051.6_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Market-oriented Skilled Agricultural Workers` = "PL051.61_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Market-oriented Skilled Forestry, Fishery and Hunting Workers` = "PL051.62_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Craft and Related Trades Workers` = "PL051.7_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Building and Related Trades Workers (excluding Electricians)` = "PL051.71_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Metal, Machinery and Related Trades Workers` = "PL051.72_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Handicraft and Printing Workers` = "PL051.73_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Electrical and Electronics Trades Workers` = "PL051.74_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Food Processing, Woodworking, Garment and Other Craft and Related Trades Workers` = "PL051.75_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Plant and Machine Operators and Assemblers` = "PL051.8_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Stationary Plant and Machine Operators` = "PL051.81_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Assemblers` = "PL051.82_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Drivers and Mobile Plant Operators` = "PL051.83_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Elementary Occupations` = "PL051.9_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Cleaners and Helpers` = "PL051.91_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Agricultural, Forestry and Fishery Labourers` = "PL051.92_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Labourers in Mining, Construction, Manufacturing and Transport` = "PL051.93_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Food Preparation Assistants` = "PL051.94_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Street and Related Sales and Services Workers` = "PL051.95_moy",
                                                                     `[PL051] Occupation (ISCO-08 (COM)) : Refuse Workers and Other Elementary Workers` = "PL051.96_moy")
)